server:
  port: 8081

spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 7341
    driver-class-name: com.mysql.cj.jdbc.Driver

#     this is used to tell config server that this service is using config server
  config:
    import: optional:configserver:http://localhost:8085
#    spring.config.import: configserver:http://localhost:8085
#    spring.profile.active: dev

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka